### ISSUE TITLE
Team to swot up on specs

### ISSUE THREAD

**Issue by dave-manta** [MantaRayMedia/eahealth#11]
### Done criteria
- [x] Decide who's in the team and then assign those bad boys

**Comment by nadia847** [comment]
@cutlern @dilwarhussain read this please before the kickoff /Files/PROJECTS/-COMPLETED/EAHRC discovery phase [552]/Scoping/REPORT/East Africa Heath Research Commission Knowledge Management Web Portal Requirements document v8.pdf
