### ISSUE TITLE
Theme search page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#126]
#### Issues

- [x] That template issue needs resolving as pagers disappear when going onto the next page sometimes
- [ ] ~Remove pagination from default search~
- [x] See spacing between search button and search field when brwser window is <=397px
- [x] ~Search title is still touching browser edge~
- [x] ~Search button should be inline with search field - search field doesn't need to be entire width of page~
- [x] ~Style first, previous, next & last pagers (Files/PROJECTS/EA Health website & directory - 579/Design/Assets/Icons/arrows/Arrow-first.svg and Arrow-last.svg) to match arrows on sliders - apply to full pagers throughout the site - including directory~

**Comment by dilwarhussain** [comment]
@nadia847 Pager breaks on second page when logged in, but works fine when logged out: http://eahealth-dev.mrmdev.co.uk/search/node/africa

Using both search templates from Remora base bar one extra class added to the content type.

**Comment by dilwarhussain** [comment]
@meldera Can you take a look at this issue, see comment above as to what is happening to search pages with multiple pages.
