### ISSUE TITLE
Core content type/nugget permissions

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#133]
#### Content types
In addition to any directory/indicator content types that are already enabled, web editors should be able to add:
- [x] Alert
- [x] Event
- [x] Health condition
- [x] Journal
- [x] News article
- [x] Organisation group
- [x] Page
- [x] Partner state
- [x] Peer-reviewed article
- [x] Person
- [x] Promo
- [x] Resource
- [x] Team
- [x] Travel
- [x] Travel requirement

#### Enabled nuggets
- [x] Attachments
- [x] FAQs
- [x] Q&A
- [x] Feed
- [x] Full width image (where appropriate - hero only?)
- [x] Photo gallery
- [x] Content block
- [x] Landing content block
- [x] Box links
- [x] Organisation group
- [x] Promo
- [x] Social links(footer only)
- [x] Statistic (partner states only)
- [x] Team
- [x] Person (Team content type only)
- [x] Video

#### Disabled/hidden nuggets
- [x] Block
- [x] Form
- [x] IFrame
- [x] World map
- [x] Slideshow
- [x] Tagged content
- [x] Twitter

**Comment by nadia847** [comment]
@cutlern @matty-manta i've got a list of what i think needs to be enabled for this round of training. 

Nelle please ensure all of these are enabled and do some testing

Matty please ensure you are able to add/edit these and there aren't any issues along the way

Let me know if you think I've missed anything from here

**Comment by matty-manta** [comment]
@nadia847 @cutlern                                

Can't add:

<b>Content types</b>

Alert
Journal
Travel
Travel requirement

<b>Nuggets</b>
Landing content block
Person

**Comment by matty-manta** [comment]
I can still add Updates and Locations
