### ISSUE TITLE
Community forums

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#135]
### Done criteria
- [ ] Embed health community forums under Health condition pages eg https://www.nhs.uk/Conditions/Asthma/Pages/Community.aspx

Awaiting response from HealthUnlocked on how to embed community forums into the site

**Comment by meldera** [comment]
http://eahealth-dev.mrmdev.co.uk/health-conditions/appendicitis
tmp context: http://eahealth-dev.mrmdev.co.uk/admin/structure/context/list/tmp/edit
@nadia847
