### ISSUE TITLE
Health indicator crumb

### ISSUE THREAD

**Issue by matty-manta** [MantaRayMedia/eahealth#139]
### Done criteria
- [x] HIV/AIDS appearing within "About EAHRC"

**Comment by dilwarhussain** [comment]
@matty-manta Fixed the issue with the broken infant mortality maps/charts too. http://eahealth-dev.mrmdev.co.uk/health-indicators/infant-mortality

**Comment by nadia847** [comment]
@matty-manta if this is fixed feel free to close it - client won;t really be reviewing anything and don't have access to github or anything.
