### ISSUE TITLE
Health condition CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#31]
## Done criteria
- [x] Build content type
- [x] Node layout
- [x] Tabs with contextual views for other content types tagged with health condition
- [x] Theming

#### Issues
- [x] Missing promo blocks to directory [Arseni]
- [x] Missing slider control styles (see directory tabs) [Nelle/Dilwar]

## Wireframes
- [ ] https://projects.invisionapp.com/d/main#/console/12443475/271164079/preview

Need each field label to be an anchor link in a sticky menu to the corresponding section below and a view of all Specialised Healthcare Services which deal with this condition on the RHS

**Comment by nadia847** [comment]
@cutlern SHould be SYmptoms not Symptons... http://eahealth-dev.mrmdev.co.uk/admin/structure/types/manage/health-condition/fields/field_symptons

**Comment by nadia847** [comment]
@dave-manta we to finalise the wireframe before we can progress much further on this one

**Comment by cutlern** [comment]
@meldera having an issue where the blocks in this view: http://eahealth-dev.mrmdev.co.uk/admin/structure/views/view/health_condition_links/edit  work fine in the view's preview but are not displaying on the node (http://eahealth-dev.mrmdev.co.uk/health-conditions/health-condition-example) or node search pages (http://eahealth-dev.mrmdev.co.uk/health-conditions/health-condition-example/news)
