### ISSUE TITLE
Organisation CT build

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#34]
### Done criteria
- [x] Build content type
- [x] Node layout
- [x] Only web editors should be able to see the Membership level field in node edit form. Hide for EAHRC theme

### Issues
- [x] Map pin popup needs styling
- [x] ~Why is there no space after the map? http://eahealth-dev.mrmdev.co.uk/directory/search/organisations/manta-ray-media~
- [x] ~Expand/collapse buggy~
- [x] ~Should not be able to add this content type to the menu~
- [x] ~Node title, Logo, Org type, country and membership level should be in Hero region (or equivalent)~
- [x] Google map missing from sidebar

### Wireframes
- https://invis.io/ZDEN71XM7

### Designs
https://invis.io/54EWV5NCP

**Comment by cutlern** [comment]
Accreditation nugget needs scoping

**Comment by matty-manta** [comment]
@cutlern http://eahealth-dev.mrmdev.co.uk/directory/search/organisations/national-institute-for-medical-research-nimr ethics expand/collapse
