### ISSUE TITLE
Specialised healthcare services CT

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#36]
### Done criteria
- [x] Build content type
- [x] Node layout
- [ ] Theming

### Issues
- [x] Each tag should be outlined separately not be in a collective box
- [x] ~Healthcare tags widget should not allow Organisation reps to add new tags, only select existing ones.~
- [x] ~Should not be able to add this content type to the menu~
- [x] ~The Organisation should not be part of the title, might get a bit long, instead the "at [organisation]" should probably be a sub heading on the next line with a link to the organisation like "National Hospital in Kenya" on organisation nodes~
- [x] ~Fix duplication and empty 'Related health conditions' sidebar box.~

### Design
- [x] Need icon or name of content type in the header to differentiate different directory content types when you're on the node
[Link to design](https://invis.io/UAF8D102S#/272324899_Hospital_V0-1)

**Comment by nadia847** [comment]
@cutlern they should not be able to add new healthcare tags, only select existing ones so the autocomplete field won't work for this. Need to use multi-select list with Chosen

**Comment by nadia847** [comment]
@dave-manta could the Country in which research is being undertaken be different from the partner state the organisation conducting the research is located in?

**Comment by nadia847** [comment]
@cat-manta work for you here

**Comment by cat-manta** [comment]
@cutlern I have added a tag to say if it's an organisation etc, and changed the member icons
