### ISSUE TITLE
Directory LP

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#38]
### Done criteria
- [x] build directory counter views
- [x] build sliders for tanzanite, sapphire and ruby organisations
- [x] themed hero
- [x] themed counters with icons
- [x] slideshows with themed pagers

### Issues
- [x] Header band texture appears in front of drop down menu
- [x] Directory counter card texture is too strong
- [x] Directory counter title is too small
- [x] Slideshow bands are the wrong colour
- [x] Border between slideshows is missing
- [x] Organisation card title too big
- [x] Spacing between cards and pagers is too big
- [x]  Pagers and arrows are too big

- [x] ~Content is using entire browser width instead of adhering to site max width~
- [x] ~Organisation views aren't slideshows~

## Wireframes
https://invis.io/UAF8D102S#/272324598_Directory-Landing

### Design
- [x] Not sure how clickable the counters look. 
- [x] Block titles don't stand out as titles with pagers that look almost the same size
- [x] Not enough spacing between pagers and the next section
- [x] Slider pagers should be dots not numbers. Like the idea of sticking with the diamond shape but smaller - also will need a hover and active state.

**Comment by cat-manta** [comment]
@cutlern The icons for the boxes at the top of this page are here:
Files/PROJECTS/EA Health website & directory [579]/Design/Assets/Graphics

**Comment by cat-manta** [comment]
@nadia847 I've updated the design, can you go through the design checklist please?

@cutlern once nadia has approved the changes, I can go through them with you if you want
