### ISSUE TITLE
Organisations search page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#39]
### Done criteria
- [x] Page title should be above directory sub menu
- [x] Search text field should autocomplete
- [x] Filter (checkbox) fields should autosubmit
- [x] Apply button should be "Search"
- [x] Move the Text search and buttons above the rest of the filters (test Mefid 
- [x] Default sort order should be by membership level 1. Tanzanite, 2. Sapphire, 3. Ruby, 4. everything else
- [x] Expose sort filter with: A-Z, Membership level
- [x] Tanzania, United republic of should just be Tanzania
- [x] Base order of fields on design below (org name, level, address, tags - partner state, org type, ownership)
- [x] 24 items per page (for all dir views)
- [x] Inherit search from list views page, keep criteria when flicking between the two
- [x] have the correct card content on opening pop up
- [x] Location address inherited from associated Organisation node
- [x] Should remember your search criteria when you navigate away from the search and subsequently return
- [x] Should remember your last preference for map vs grid view
- [x] Each map view should have it's own separate preference with the grid view as the default

### Issues
- [x] When click twice on map, the view change to grid, but the button is still active
- [x] Directory tabs need to be responsive - see mobile/tablet designs
- [x] Make filters expandy and collapsy on mobile
- [x] ~Name of org is in the popup twice - should only be there once for the heading~
- [x] ~Map view: Type of org should be after the address~
- [x] ~List view: Address is missing. Should show location fields not contact field~
- [x] ~Theme map view popups~

### Wireframes
https://invis.io/PREN6ZZ3C
https://invis.io/ZCEU24BDM

### Designs
Mobile: https://projects.invisionapp.com/d/main#/console/13016505/272324601/preview
Tablet: https://projects.invisionapp.com/d/main#/console/13016505/272324602/preview
List view: https://projects.invisionapp.com/d/main#/console/12443475/266579017/preview
List hover: https://projects.invisionapp.com/d/main#/console/12443475/269274918/preview
Map view: https://projects.invisionapp.com/d/main#/console/12443475/269720255/preview

**Comment by nadia847** [comment]
@dave-manta map designs - https://invis.io/W8F06FIZE

**Comment by cat-manta** [comment]
@dilwarhussain I have updated the tablet and mobile designs of this page with the slider arrow
