### ISSUE TITLE
Organisations search - Map view

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#46]
### Done criteria
- [x] Inherit search from list views page, keep criteria when flicking between the two
- [x] have the correct card content on opening pop up
- [x] Location address inherited from associated Organisation node
- [x] Should remember your search criteria when you navigate away from the search and subsequently return
- [x] Should remember your last preference for map vs grid view
- [x] Each map view should have it's own separate preference with the grid view as the default

### Issues
- [x] Name of org is in the popup twice - should only be there once for the heading
- [x] Type of org should be after the address

### Wireframes
https://invis.io/ZCEU24BDM

**Comment by nadia847** [comment]
@meldera Added some issues

**Comment by meldera** [comment]
Re:
 Name of org is in the popup twice - should only be there once for the heading - This is necessary. Will be hidden by styles.
 Type of org should be after the address - Not according to the wireframes.

**Comment by nadia847** [comment]
@meldera I'm aware of that Arseni,that was correct at time of wireframing but the design supersedes wireframe and therefore it should now be after, as was mentioned when I briefed you. We can move when we theme though.

**Comment by nadia847** [comment]
@dave-manta map designs - https://invis.io/W8F06FIZE
