### ISSUE TITLE
Admin directory content management

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#53]
### Done criteria
This is for EA health staff (web editors) to see all directory content types only
- [x] Filter by organisation, title, type, author
- [x] Bulk update node author and publish settings
- [x] View result count

http://eahealth-dev.mrmdev.co.uk/admin/content/directory

#### Issues
- [x] Use Chosen for organisation field
- [x] Instead of admin menu, have this page as a tab on the regular Admin content page (see https://www.alnap.org/admin/content)

**Comment by cutlern** [comment]
@nadia847 http://eahealth-dev.mrmdev.co.uk/admin/directory-content
