### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#74]
### Done criteria
- [x] Build
- [x] Theme

### Issues
- [x] Make footer grey
- [x] Footer H2 is too big
- [x] Sponsored tex is too small
- [x] Line between Privacy and Disclaimer links is too tall
- [x] ~Partner logos should be inline, not stacked unless the breakpoint calls for it~
- [x] ~Order of sponsored logo content~
- [x] ~Size of sponsored logo~
- [x] ~Missing linkedin icon~

**Comment by cutlern** [comment]
Organisation group entity relationship is causing the other 3 blocks to not show when logged out
