### ISSUE TITLE
Views title field template

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#76]
views-view-field--title.tpl.php prevents HTML from Global: Custom text fields from rendering in the theme, though the markup works fine in views templates. Currently disabled but needs to be fixed so we can ensure any formatting tags (e.g. bold, italics) used in titles are correctly processed and do not display in views titles

**Comment by meldera** [comment]
@nadia I'd need a link with an example of the issue in action to proceed, please.

**Comment by nadia847** [comment]
@meldera this view has Global: Custom text fields in it: http://eahealth-dev.mrmdev.co.uk/admin/structure/views/view/directory_header/edit

Appears here: http://eahealth-dev.mrmdev.co.uk/directory/search/organisations/manta-ray-media

None of the wrappers were appearing before but seems to be resolved now :/
