### ISSUE TITLE
Parent and child organisation views

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#78]
### Done criteria
- [ ] Show child organisations on parent orgs
- [ ] Show parent organisations on child orgs

**Comment by nadia847** [comment]
@dave-manta is Subsidiaries a better term to use than "sub organisations"? 

http://eahealth-dev.mrmdev.co.uk/directory/search/organisations/manta-ray-media
http://eahealth-dev.mrmdev.co.uk/the-directory/search/organisations/tanzanite-child-organisation

**Comment by dave-manta** [comment]
@nadia847 could we just title it "Other locations"?

**Comment by nadia847** [comment]
But they're not really locations.

"Also part of this organisation"
"Related organisations"

Maybe locations could work for some organisation types.

St Bart's trust have "discover our hospitals". Not sure how helpful that is


On 9 Jan 2018, at 19:51, dave-manta <notifications@github.com<mailto:notifications@github.com>> wrote:


@nadia847<https://github.com/nadia847> could we just title it "Other locations"?

**Comment by dave-manta** [comment]
I think if an organisation is split it is because it is at a separate location, but if coils be wrong. Happy to go with also part of this org. We can always change later.
________________________________
