### ISSUE TITLE
Clunky directory search filters

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#79]
- [ ] When hitting clear all, the page should grey out like when applying filters and preventing you clicking anything

- [x] Clicking filters results in the page greying out as though loading but takes a really long time. I've not really waited log enough to see if it ever bothers to load after about 30 seconds because i just give up

- [x] Clear all doesn't always work; the page greys out and reloads but the results are still filtered and the filters are not cleared.
 
- [x] Drop downs have multiple arrows

- [x] Moving filters when search has been applied (after ajax)

- [x] Moving results and list/map toggle when search has been applied (after ajax)

**Comment by meldera** [comment]
Re: Moving results and list/map toggle when search has been applied (after ajax)

Please F5...

**Comment by dave-manta** [comment]
@nadia847 do I need to do something on this one?

**Comment by nadia847** [comment]
Not yet. I've sent it back into the backlog for the clear filters fix. There was another issue with the filters that I can't remember that you might though

On 9 Jan 2018, at 19:52, dave-manta <notifications@github.com<mailto:notifications@github.com>> wrote:


@nadia847<https://github.com/nadia847> do I need to do something on this one?

**Comment by meldera** [comment]
"When hitting clear all, the page should grey out like when applying filters and preventing you clicking anything"

This will not be fixed. Considering the complexity of views and all issues with ajax, the fact that it works at all is already an acceptable compromise.
