### ISSUE TITLE
Home page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#80]
### Done criteria
- [x] Intro section with map and title
- [x] Strap
- [x] Landing page blocks
- [x] Promo

#### Issues
- [x] First landing page block needs background
- [x] Nav text should be next to search icon
- [x] 'Now with coverage' text on an event changes colour on hover, it shouldn't do anything
- [x] I have updated the [promo hover design](https://invis.io/UAF8D102S#/272532510_Content-Page-Hovers)
- [x] The blue 'About EAHRC' box link should be like the others in the same row

---
### Wireframes
- [ ] https://projects.invisionapp.com/d/main#/console/12443475/271624627/preview

---
### Designs
- [ ] https://invis.io/UAF8D102S#/272323672_Home_V0-1

**Comment by cat-manta** [comment]
@nadia847 I've added issues at the top
