### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#82]
### Issues
- [ ] not adding icon to home screen on iOS

**Comment by cat-manta** [comment]
Favicon file location:
Files/PROJECTS/EA Health website & directory - 579/Branding/Favicon/favicons

Favicon code:

<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#0776df">
<meta name="theme-color" content="#ffeb00">

**Comment by nadia847** [comment]
@cutlern arseni fixed this when it was happening on alnap or something so you can discuss with him

**Comment by dilwarhussain** [comment]
This may not be working while the site is password protected according to this: https://stackoverflow.com/questions/7885393/apple-touch-icon-isnt-showing-up-on-the-home-screen
Also not working on BGS dev, but working fine on ALNAP dev which currently is not password protected.
