### ISSUE TITLE
News search page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#89]
### Done criteria
- [x] News cards
- [x] Filters - text, partner state, news type
- [x] Sort by - most recent, most popular

#### Issues
- [x] Equal heights breaks after ajax runs

- [x] ~Sort filter touching edge of browser window under 720px?~
- [x] ~Sort filter and result count not lined up~
- [x] ~News article should be a news type and make the field required~
- [x] ~Search field should be using search terms looking through the entire node, not just a title with autocomplete~
- [x] ~*Apply* button should be renamed to *Search* ~
- [x] ~too much space between card type and card title~
- [x] ~card titles too big~
- [x] ~card title line-height is too small~
- [x] ~sort dropdown doesn't need to use Chosen~
- [x] ~sort dropdown touches the filter box under 960px~

---
### Designs
- [ ] https://projects.invisionapp.com/d/main#/console/13016505/272325069/preview

**Comment by nadia847** [comment]
@dilwarhussain @cutlern  there's a point between 540px and 588px when the filters are stacking but not full width

It works fine on events page so i hope you're not making these styles specific

**Comment by dilwarhussain** [comment]
@nadia847 Match heights not working after ajax runs on block views with filters. Works fine on all page views i.e. http://eahealth-dev.mrmdev.co.uk/policy-publications. @meldera Could you take a look please.

**Comment by dilwarhussain** [comment]
@meldera Never mind, we're going to rebuild view as page view :)
