### ISSUE TITLE
Past events page

### ISSUE THREAD

**Issue by nadia847** [MantaRayMedia/eahealth#94]
### Done criteria
- [x] Indicator for events with coverage
- [x] Filters - text, partner state, event type, has event coverage, location

---
### Issues
- [x] ~Event coverage filter should be last~
- [x] Cards should be 4 in a row, not 6.
- [x] ~Filters need to be spaced on mobile~
- [x] ~Has coverage filter should not be wider than drop downs when stacked~
- [x] ~row-max-6 on tablet - card margin-right is wrong~
- [x] Checkbox fields without any options should not look like text input fields. Make them look disabled please.
- [x] ~Fields should not have different coloured borders - looks weird. make the same (lightest, checkboxes one)~
- [x] ~Main content region - white shadowed box - is touching edges of my browser window. needs a 10px space~

---
### Designs
Updated coverage indicator appears on:
- [x] [Event node](https://invis.io/UAF8D102S#/274180289_Events)
- [x] [Card on past events page](https://invis.io/UAF8D102S#/272324900_Country_V0-1)

**Comment by dilwarhussain** [comment]
@nadia847 What do you mean by "row-max-6 on tablet - card margin-right is wrong"? I'm not using 6 in a row anymore because of "Cards should be 4 in a row, not 6.".

**Comment by nadia847** [comment]
@dilwarhussain they can still apply 6 in a row elsewhere so this should work

**Comment by dilwarhussain** [comment]
@nadia847 Gotcha, fixed.

**Comment by nadia847** [comment]
@dilwarhussain got there eventually 😛
