### ISSUE TITLE
Link field bug

### ISSUE THREAD

**Issue by dilwarhussain** [MantaRayMedia/eahealth#98]
Link field title is removed when a nugget is added to event content type. Might be occurring on other content types but have not tested.

Example
Event with no nuggets: http://eahealth-dev.mrmdev.co.uk/node/30/edit
Event with 1 main content nugget: http://eahealth-dev.mrmdev.co.uk/node/598/edit

**Comment by nadia847** [comment]
@dilwarhussain i'm not experiencing the bug. is this fixed for you too?

**Comment by dilwarhussain** [comment]
@nadia847 Yep it's fixed
